services:
  judge0:
    image: yozuru/judge0:latest
    build:
      context: .
      target: production
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "2358:2358"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true
    env_file: judge0.conf
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=development_secret_key_base_placeholder

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    # restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    # restart: always

volumes:
  data:
